### ISSUE TITLE
Wrong default branch name

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/codemirror#3]
The default branch should be named `main`.

**Comment by griimick** [comment]
@nekowinston I don't see the "Default branch" section under General Settings. It might be because of permissions. Can you check it out? There should be a "Rename branch" option.

It shouldn't break any submodule references as they reference commits that don't change on renaming branches.

**Comment by nekowinston** [comment]
I've renamed it for you, I just created the issues as a checklist for myself via a script yesterday.

Looks like we'll have to re-deploy the GH pages:
<img width="412" alt="image" src="https://github.com/catppuccin/codemirror/assets/79978224/fb30fae3-2a87-4b2b-886b-c95d8f531386">
